### PR TITLE
Simplify model calls

### PR DESCRIPTION
**Pull request by gnuoy**
Move calls to get_juju_model() down into run_in_model

### CODE REVIEW

**Comment by thedac** [comment]
Let's discuss IRL. We seem to have duplicated the add and destroy model functions in a previous PR. See zaza/controller.py. A consequence of using add_model is that it does not set the new model as the current model which leads to some odd behavior.

I tested with a second model running and things "worked" in that it targeted the correct model, but it had a lot of warning outputs. We need to test this a bit more before landing.

**Comment by gnuoy** [comment]
I don't think the warning outputs are to do with this pr, they seem to be to do with a call to close the event loop when it is already closed. I will create a separate pr with a fix. fwiw I have run the bgp and vault tests successfully against  this this pr.

**Comment by gnuoy** [comment]
thedac, I was wrong about the issue being to do with the event loop not being closed properly, it was to do with the poor implementation of add_model and destroy_model in zaza.model. I have removed these duplicates here: https://github.com/openstack-charmers/zaza/pull/65 . The errors/warning are now gone.

**Comment by thedac** [comment]
I did the PRs in the wrong order and then bungled an attempt to fix the conflicts. I am going to quit while I am behind. I am +1 on this change please carefully update the PR to represent current reality on master.

**Pull request merged**
