### PR TITLE
Fix invalid args reference

### PR DESCRIPTION
**Pull request by ionutbalutoiu**
Quick fix for the new functionality from https://github.com/openstack-charmers/zaza/pull/426

### CODE REVIEW

**Review by ajkavanagh — APPROVED** [review]

**Review by ChrisMacNaughton — COMMENTED** [review]
This change is actually incorrect, as the deploy.py does only take a single bundle, and isn't the same code paths as the previous commit

**Comment by ajkavanagh** [comment]
> This change is actually incorrect, as the deploy.py does only take a single bundle, and isn't the same code paths as the previous commit

We could revert it, I suppose?

**Comment by ChrisMacNaughton** [comment]
Proposed at https://github.com/openstack-charmers/zaza/pull/429 , but @AurelienLourot is concerned that this change is currently incorrect

**Comment by AurelienLourot** [comment]
no that's fine, I got it straight now :) @ionutbalutoiu in fact when you got hit by the issue in a gerrit review, all you needed was #427. #428 here is not correct and so reverting it with #429 is a good move :)

**Comment by ionutbalutoiu** [comment]
Sorry for the noise guys. I didn't carefully look at the code paths to make sure #428 is not really needed.

Thank-you for reverting it!

**Pull request merged**
