### PR TITLE
Test get_subordinates()

### PR DESCRIPTION
**Pull request by freyes**
This patch adds the ntp charm and relates it the ubuntu application,
then get_subordinates() is exercised in a test.

### CODE REVIEW

**Comment by freyes** [comment]
Testing get_subordinates() since this failure is being hit in the CI - https://openstack-ci-reports.ubuntu.com/artifacts/e75/852578/1/check/focal-yoga/e75a86b/

**Comment by freyes** [comment]
Hi @ajkavanagh , this pull request is ready for review, it will be easier to review if go commit by commit, I tried to keep each logical change in its own commit since we will need to backport 8f0dcf4 to `stable/yoga` to unblock hacluster backports to `stable/jammy`.

Best,

**Review by ajkavanagh — APPROVED** [review]
All looks good to me; essentially this is a nice paper-over the issue in libjuju until it is fixed.  We may have to backport this, though which is a bit of a pain.  Maybe osci should grow the ability to indicate which juju the bundle should be tested with?

**Comment by freyes** [comment]
On Tue, 2022-08-23 at 02:50 -0700, Alex Kavanagh wrote:
> @ajkavanagh approved this pull request.
> All looks good to me; essentially this is a nice paper-over the issue in libjuju until it is
> fixed.  We may have to backport this, though which is a bit of a pain. Maybe osci should grow the
> ability to indicate which juju the bundle should be tested with?

mmmmh, probably not, I believe a good place to test libjuju against multiple juju versions is right
here in zaza, something we should do is to increase the number of functional tests we have, maybe
test against */edge channels even.

re: juju edge testing, it would be nice that those are configured like "non-voting" job, so we get
feedback, but they do not block the gate, although that's not possible according to this
https://github.com/actions/toolkit/issues/399 , it's being spec'ed though
https://github.com/community/community/discussions/15452

**Pull request merged**
